/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class kernelJNI {
  public final static native void setArrays(float[] jarg1, int jarg2, int jarg3, float[] jarg4, int jarg5, int jarg6);
  public final static native void migrateCPU(double[] jarg1, int[] jarg2, double[] jarg3, double[] jarg4, long[] jarg5, int jarg6);
}
