/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class DispersalFunctionCJNI {
  public final static native void setArrays(double[] jarg1, float[] jarg2, int[] jarg3, int[] jarg4, float[] jarg5, int[] jarg6, int[] jarg7);
  public final static native void migrate(double[] jarg1, double jarg2, int[] jarg3, int[] jarg4, double[] jarg5, int jarg6);
}
